### ISSUE TITLE
Spinner is not defined

### ISSUE THREAD

**Issue by MiltosD** [foxbenjaminfox/meteor-loading#3]
Hello, 
I'm not sure if this is a bug or it is my wrong but i get an "Uncaught ReferenceError: Spinner is not defined" on line 44 in loading.js...

I tried to use it as 

`Loading.call("method", data, (error)=> {...`

Thank you

**Comment by foxbenjaminfox** [comment]
In the new version of Meteor, 1.3, they changed the way packages need to declare what they import and export. That broke more than a few packages, including this one.

I wrote an update to fix this, but I didn't get around to polishing it off and publishing it until now. Your issue gave me the motivation I needed to actually get around to publishing it, so good work!

Update to the newest version of this package with `meteor update xyz:loading`, and it should work. If you have any more troubles with it, let me know.

**Comment by MiltosD** [comment]
Yep it's working now. Thank you so much. I'll spread the word!
