### ISSUE TITLE
How import xyz:loading?

### ISSUE THREAD

**Issue by CharlesIrvineKC** [foxbenjaminfox/meteor-loading#4]
What is the proper import statement to import Loading into my Meteor code?

I've tried 

`import Loading from "xyz:loading`

but that doesn't work. I get an unable to resolve module error.

**Comment by foxbenjaminfox** [comment]
First, you need to [install it using the `meteor add` command](https://docs.meteor.com/commandline.html#meteoradd):

`$ meteor add xyz:loading`

Then, as it's an atmosphere package, you need to [import it with a `meteor/` prefix](https://guide.meteor.com/using-atmosphere-packages.html#using-atmosphere):

`import { Loading } from "meteor/xyz:loading"`

Then it will work.
